
use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods', :disable_input_output_paths => true

platform :ios, '12.0'

target 'PredictorSDK' do
  pod 'predictorShared', :path => '../predictorShared'
end

target 'iosApp' do

  pod 'predictorShared', :path => '../predictorShared'

  pod 'Kingfisher'
  pod 'PinLayout'

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'

  pod 'Alidade'
  pod 'Alidade/Associatable'
  pod 'Alidade/Flowable'
  pod 'Alidade/FormatterPool'
  pod 'Alidade/UI'
  pod 'Alidade/String'

  pod 'Astrolabe'
  pod 'Sundial'

	pod 'Firebase'
	pod 'Firebase/Crashlytics'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
      if config.name == 'Debug'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        else
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      end
    end
  end
end

